/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const HomeLazyImport = createFileRoute('/home')()
const IndexLazyImport = createFileRoute('/')()
const HomeRestaurantsLazyImport = createFileRoute('/home/restaurants')()
const HomeMeLazyImport = createFileRoute('/home/me')()
const HomeUserIdLazyImport = createFileRoute('/home/$userId')()

// Create/Update Routes

const HomeLazyRoute = HomeLazyImport.update({
  path: '/home',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/home.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const HomeRestaurantsLazyRoute = HomeRestaurantsLazyImport.update({
  path: '/restaurants',
  getParentRoute: () => HomeLazyRoute,
} as any).lazy(() =>
  import('./routes/home.restaurants.lazy').then((d) => d.Route),
)

const HomeMeLazyRoute = HomeMeLazyImport.update({
  path: '/me',
  getParentRoute: () => HomeLazyRoute,
} as any).lazy(() => import('./routes/home.me.lazy').then((d) => d.Route))

const HomeUserIdLazyRoute = HomeUserIdLazyImport.update({
  path: '/$userId',
  getParentRoute: () => HomeLazyRoute,
} as any).lazy(() => import('./routes/home.$userId.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeLazyImport
      parentRoute: typeof rootRoute
    }
    '/home/$userId': {
      id: '/home/$userId'
      path: '/$userId'
      fullPath: '/home/$userId'
      preLoaderRoute: typeof HomeUserIdLazyImport
      parentRoute: typeof HomeLazyImport
    }
    '/home/me': {
      id: '/home/me'
      path: '/me'
      fullPath: '/home/me'
      preLoaderRoute: typeof HomeMeLazyImport
      parentRoute: typeof HomeLazyImport
    }
    '/home/restaurants': {
      id: '/home/restaurants'
      path: '/restaurants'
      fullPath: '/home/restaurants'
      preLoaderRoute: typeof HomeRestaurantsLazyImport
      parentRoute: typeof HomeLazyImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  HomeLazyRoute: HomeLazyRoute.addChildren({
    HomeUserIdLazyRoute,
    HomeMeLazyRoute,
    HomeRestaurantsLazyRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/home"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/home": {
      "filePath": "home.lazy.tsx",
      "children": [
        "/home/$userId",
        "/home/me",
        "/home/restaurants"
      ]
    },
    "/home/$userId": {
      "filePath": "home.$userId.lazy.tsx",
      "parent": "/home"
    },
    "/home/me": {
      "filePath": "home.me.lazy.tsx",
      "parent": "/home"
    },
    "/home/restaurants": {
      "filePath": "home.restaurants.lazy.tsx",
      "parent": "/home"
    }
  }
}
ROUTE_MANIFEST_END */
